spring.application.name=support-service
server.port=8085

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventual
spring.datasource.username=postgres
spring.datasource.password=postgres
