spring.application.name=event-service
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventual
spring.datasource.username=postgres
spring.datasource.password=postgres

# File storage
upload.dir=uploads

# User Service URL (for sync calls)
user.service.url=http://localhost:8082

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
