spring.application.name=eventual-layered
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/eventual
spring.datasource.name=eventual
spring.datasource.username=postgres
spring.datasource.password=postgres1

spring.devtools.restart.additional-paths=src/main/resources/static/

jwt.secret=ZXZlbnR1YWwtc2VjcmV0LWtleS1mb3ItanctYXV0aGVudGljYXRpb24tMjAyNA==

file.upload-dir=uploads
